Add white-spaces at end of multi-line error messages.
Currently, the message printed shows as

ValueError: We cannot assign an empty TensorSpecStruct.Please, first fill another TensorSpecStruct andadd it to this instance.

Note the missing spaces at TensorSpecStruct.Please and andadd.

PiperOrigin-RevId: 357311262